import { env } from "cloudflare:workers";
import type { Asset, CreateAssetInput, UpdateAssetInput } from "./contracts";
import { DEFAULT_TENANT_ID } from "./tenant-context";

type AssetRow = { id: string; tenant_id: string; name: string; type: Asset["type"]; owner: string; status: Asset["status"]; created_at: string };
const memory = globalThis as typeof globalThis & { nexeraAssets?: Asset[] };
function getMemory() { memory.nexeraAssets ??= []; return memory.nexeraAssets; }
function map(row: AssetRow): Asset { return { id: row.id, tenantId: row.tenant_id, name: row.name, type: row.type, owner: row.owner, status: row.status, createdAt: row.created_at }; }
async function ensureTable() { if (!env.DB) return false; await env.DB.prepare("create table if not exists assets (id text primary key, tenant_id text not null, name text not null, type text not null, owner text not null, status text not null, created_at text not null)").run(); return true; }

export async function listAssets(tenantId = DEFAULT_TENANT_ID) { try { if (await ensureTable()) { const rows = await env.DB.prepare("select * from assets where tenant_id = ? order by name").bind(tenantId).all<AssetRow>(); return rows.results.map(map); } } catch { /* Use memory fallback when D1 is unavailable. */ } return getMemory().filter((asset) => asset.tenantId === tenantId); }
export async function createAsset(input: CreateAssetInput, tenantId = DEFAULT_TENANT_ID) { const asset: Asset = { id: `asset-${crypto.randomUUID()}`, tenantId, name: input.name.trim(), type: input.type, owner: input.owner.trim(), status: "Activo", createdAt: new Date().toISOString() }; if (!asset.name || !asset.owner) throw new Error("name and owner are required"); try { if (await ensureTable()) { await env.DB.prepare("insert into assets (id, tenant_id, name, type, owner, status, created_at) values (?, ?, ?, ?, ?, ?, ?)").bind(asset.id, asset.tenantId, asset.name, asset.type, asset.owner, asset.status, asset.createdAt).run(); return asset; } } catch { /* Fall through to the local store. */ } getMemory().push(asset); return asset; }
export async function updateAsset(id: string, input: UpdateAssetInput, tenantId = DEFAULT_TENANT_ID) { try { if (await ensureTable()) { const current = await env.DB.prepare("select * from assets where id = ? and tenant_id = ?").bind(id, tenantId).first<AssetRow>(); if (!current) return null; const next = { ...map(current), ...input }; await env.DB.prepare("update assets set name = ?, type = ?, owner = ?, status = ? where id = ? and tenant_id = ?").bind(next.name, next.type, next.owner, next.status, id, tenantId).run(); return next; } } catch { /* Fall through to memory. */ } const store = getMemory(); const index = store.findIndex((item) => item.id === id && item.tenantId === tenantId); if (index < 0) return null; store[index] = { ...store[index], ...input }; return store[index]; }
export async function deleteAsset(id: string, tenantId = DEFAULT_TENANT_ID) { try { if (await ensureTable()) return Boolean((await env.DB.prepare("delete from assets where id = ? and tenant_id = ?").bind(id, tenantId).run()).meta.changes); } catch { /* Fall through to memory. */ } const store = getMemory(); const before = store.length; memory.nexeraAssets = store.filter((item) => !(item.id === id && item.tenantId === tenantId)); return memory.nexeraAssets.length < before; }
