import { env } from "cloudflare:workers";
import type { CustomField } from "./contracts";
import { DEFAULT_TENANT_ID } from "./tenant-context";
type Row = { id: string; tenant_id: string; name: string; applies_to: CustomField["appliesTo"]; type: CustomField["type"]; required: number; created_at: string };
const memory = globalThis as typeof globalThis & { nexeraCustomFields?: CustomField[] };
function map(row: Row): CustomField { return { id: row.id, tenantId: row.tenant_id, name: row.name, appliesTo: row.applies_to, type: row.type, required: Boolean(row.required), createdAt: row.created_at }; }
async function table() { if (!env.DB) return false; await env.DB.prepare("create table if not exists custom_fields (id text primary key, tenant_id text not null, name text not null, applies_to text not null, type text not null, required integer not null, created_at text not null)").run(); return true; }
export async function listCustomFields(tenantId = DEFAULT_TENANT_ID) { try { if (await table()) { const rows = await env.DB.prepare("select * from custom_fields where tenant_id = ? order by name").bind(tenantId).all<Row>(); return rows.results.map(map); } } catch { /* Use memory fallback. */ } return (memory.nexeraCustomFields ?? []).filter((item) => item.tenantId === tenantId); }
export async function createCustomField(input: Omit<CustomField, "id" | "tenantId" | "createdAt">, tenantId = DEFAULT_TENANT_ID) { const item: CustomField = { ...input, id: `field-${crypto.randomUUID()}`, tenantId, createdAt: new Date().toISOString() }; if (!item.name.trim()) throw new Error("name is required"); try { if (await table()) { await env.DB.prepare("insert into custom_fields (id, tenant_id, name, applies_to, type, required, created_at) values (?, ?, ?, ?, ?, ?, ?)").bind(item.id, tenantId, item.name.trim(), item.appliesTo, item.type, item.required ? 1 : 0, item.createdAt).run(); return item; } } catch { /* Fall through to memory. */ } memory.nexeraCustomFields ??= []; memory.nexeraCustomFields.push(item); return item; }
export async function deleteCustomField(id: string, tenantId = DEFAULT_TENANT_ID) { try { if (await table()) return Boolean((await env.DB.prepare("delete from custom_fields where id = ? and tenant_id = ?").bind(id, tenantId).run()).meta.changes); } catch { /* Fall through to memory. */ } const current = memory.nexeraCustomFields ?? []; const before = current.length; memory.nexeraCustomFields = current.filter((item) => !(item.id === id && item.tenantId === tenantId)); return memory.nexeraCustomFields.length < before; }
