import { env } from "cloudflare:workers";
import type { CreateTechnicianGroupInput, TechnicianGroup, UpdateTechnicianGroupInput } from "./contracts";
import { DEFAULT_TENANT_ID } from "./tenant-context";
type Row = { id: string; tenant_id: string; name: string; specialty: string; status: TechnicianGroup["status"]; created_at: string };
const memory = globalThis as typeof globalThis & { nexeraTechnicianGroups?: TechnicianGroup[] };
function getMemory() { memory.nexeraTechnicianGroups ??= []; return memory.nexeraTechnicianGroups; }
function map(row: Row): TechnicianGroup { return { id: row.id, tenantId: row.tenant_id, name: row.name, specialty: row.specialty, status: row.status, createdAt: row.created_at }; }
function hasDatabase() { return Boolean(env.DB); }
export async function listTechnicianGroups(tenantId = DEFAULT_TENANT_ID) { try { if (hasDatabase()) { const rows = await env.DB.prepare("select * from technician_groups where tenant_id = ? order by name").bind(tenantId).all<Row>(); return rows.results.map(map); } } catch { /* Use memory fallback when D1 is unavailable. */ } return getMemory().filter((item) => item.tenantId === tenantId); }
export async function createTechnicianGroup(input: CreateTechnicianGroupInput, tenantId = DEFAULT_TENANT_ID) { const item: TechnicianGroup = { id: `group-${crypto.randomUUID()}`, tenantId, name: input.name.trim(), specialty: input.specialty.trim(), status: "Activo", createdAt: new Date().toISOString() }; if (!item.name || !item.specialty) throw new Error("name and specialty are required"); try { if (hasDatabase()) { await env.DB.prepare("insert into technician_groups (id, tenant_id, name, specialty, status, created_at) values (?, ?, ?, ?, ?, ?)").bind(item.id, item.tenantId, item.name, item.specialty, item.status, item.createdAt).run(); return item; } } catch { /* Fall through to the local store. */ } getMemory().push(item); return item; }
export async function updateTechnicianGroup(id: string, input: UpdateTechnicianGroupInput, tenantId = DEFAULT_TENANT_ID) { try { if (hasDatabase()) { const current = await env.DB.prepare("select * from technician_groups where id = ? and tenant_id = ?").bind(id, tenantId).first<Row>(); if (!current) return null; const next = { ...map(current), ...input }; await env.DB.prepare("update technician_groups set name = ?, specialty = ?, status = ? where id = ? and tenant_id = ?").bind(next.name, next.specialty, next.status, id, tenantId).run(); return next; } } catch { /* Fall through to memory. */ } const store = getMemory(); const index = store.findIndex((item) => item.id === id && item.tenantId === tenantId); if (index < 0) return null; store[index] = { ...store[index], ...input }; return store[index]; }
export async function deleteTechnicianGroup(id: string, tenantId = DEFAULT_TENANT_ID) { try { if (hasDatabase()) return Boolean((await env.DB.prepare("delete from technician_groups where id = ? and tenant_id = ?").bind(id, tenantId).run()).meta.changes); } catch { /* Fall through to memory. */ } const store = getMemory(); const before = store.length; memory.nexeraTechnicianGroups = store.filter((item) => !(item.id === id && item.tenantId === tenantId)); return memory.nexeraTechnicianGroups.length < before; }
