import { env } from "cloudflare:workers";
import type { CreateTicketTemplateInput, TicketTemplate, UpdateTicketTemplateInput } from "./contracts";
import { DEFAULT_TENANT_ID } from "./tenant-context";

type Row = { id: string; tenant_id: string; name: string; subject: string; body: string; created_at: string };
const memory = globalThis as typeof globalThis & { nexeraTicketTemplates?: TicketTemplate[] };
function getMemory() { memory.nexeraTicketTemplates ??= []; return memory.nexeraTicketTemplates; }
function map(row: Row): TicketTemplate { return { id: row.id, tenantId: row.tenant_id, name: row.name, subject: row.subject, body: row.body, createdAt: row.created_at }; }
async function ensureTable() { if (!env.DB) return false; await env.DB.prepare("create table if not exists ticket_templates (id text primary key, tenant_id text not null, name text not null, subject text not null, body text not null, created_at text not null)").run(); return true; }
export async function listTicketTemplates(tenantId = DEFAULT_TENANT_ID) { try { if (await ensureTable()) { const rows = await env.DB.prepare("select * from ticket_templates where tenant_id = ? order by name").bind(tenantId).all<Row>(); return rows.results.map(map); } } catch { /* Use memory fallback when D1 is unavailable. */ } return getMemory().filter((item) => item.tenantId === tenantId); }
export async function createTicketTemplate(input: CreateTicketTemplateInput, tenantId = DEFAULT_TENANT_ID) { const item: TicketTemplate = { id: `template-${crypto.randomUUID()}`, tenantId, name: input.name.trim(), subject: input.subject.trim(), body: input.body.trim(), createdAt: new Date().toISOString() }; if (!item.name || !item.subject || !item.body) throw new Error("name, subject and body are required"); try { if (await ensureTable()) { await env.DB.prepare("insert into ticket_templates (id, tenant_id, name, subject, body, created_at) values (?, ?, ?, ?, ?, ?)").bind(item.id, item.tenantId, item.name, item.subject, item.body, item.createdAt).run(); return item; } } catch { /* Fall through to the local store. */ } getMemory().push(item); return item; }
export async function updateTicketTemplate(id: string, input: UpdateTicketTemplateInput, tenantId = DEFAULT_TENANT_ID) { try { if (await ensureTable()) { const current = await env.DB.prepare("select * from ticket_templates where id = ? and tenant_id = ?").bind(id, tenantId).first<Row>(); if (!current) return null; const next = { ...map(current), ...input }; await env.DB.prepare("update ticket_templates set name = ?, subject = ?, body = ? where id = ? and tenant_id = ?").bind(next.name, next.subject, next.body, id, tenantId).run(); return next; } } catch { /* Fall through to memory. */ } const store = getMemory(); const index = store.findIndex((item) => item.id === id && item.tenantId === tenantId); if (index < 0) return null; store[index] = { ...store[index], ...input }; return store[index]; }
export async function deleteTicketTemplate(id: string, tenantId = DEFAULT_TENANT_ID) { try { if (await ensureTable()) return Boolean((await env.DB.prepare("delete from ticket_templates where id = ? and tenant_id = ?").bind(id, tenantId).run()).meta.changes); } catch { /* Fall through to memory. */ } const store = getMemory(); const before = store.length; memory.nexeraTicketTemplates = store.filter((item) => !(item.id === id && item.tenantId === tenantId)); return memory.nexeraTicketTemplates.length < before; }
