import { requirePermission } from "@/lib/nexera/auth-store";
import { createTicketTemplate, deleteTicketTemplate, listTicketTemplates, updateTicketTemplate } from "@/lib/nexera/ticket-template-store";
import { tenantIdFromRequest } from "@/lib/nexera/tenant-context";
import type { TicketTemplate } from "@/lib/nexera/contracts";

export async function GET(request: Request) { const authorization = await requirePermission(request, "user:read"); if (!authorization.allowed) return authorization.response; return Response.json({ data: await listTicketTemplates(await tenantIdFromRequest(request)) }); }
export async function POST(request: Request) { const authorization = await requirePermission(request, "user:update"); if (!authorization.allowed) return authorization.response; const body = (await request.json().catch(() => ({}))) as Partial<TicketTemplate>; try { const data = await createTicketTemplate({ name: String(body.name ?? ""), subject: String(body.subject ?? ""), body: String(body.body ?? "") }, await tenantIdFromRequest(request)); return Response.json({ data }, { status: 201 }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Could not create template" }, { status: 400 }); } }
export async function PATCH(request: Request) { const authorization = await requirePermission(request, "user:update"); if (!authorization.allowed) return authorization.response; const body = (await request.json().catch(() => ({}))) as Partial<TicketTemplate>; if (typeof body.id !== "string") return Response.json({ error: "id is required" }, { status: 400 }); const data = await updateTicketTemplate(body.id, { name: typeof body.name === "string" ? body.name.trim() : undefined, subject: typeof body.subject === "string" ? body.subject.trim() : undefined, body: typeof body.body === "string" ? body.body.trim() : undefined }, await tenantIdFromRequest(request)); if (!data) return Response.json({ error: "Template not found" }, { status: 404 }); return Response.json({ data }); }
export async function DELETE(request: Request) { const authorization = await requirePermission(request, "user:update"); if (!authorization.allowed) return authorization.response; const id = new URL(request.url).searchParams.get("id"); if (!id || !(await deleteTicketTemplate(id, await tenantIdFromRequest(request)))) return Response.json({ error: "Template not found" }, { status: 404 }); return Response.json({ data: { deleted: true } }); }
