import { requirePermission } from "@/lib/nexera/auth-store";
import { createAsset, deleteAsset, listAssets, updateAsset } from "@/lib/nexera/asset-store";
import { tenantIdFromRequest } from "@/lib/nexera/tenant-context";
import type { Asset } from "@/lib/nexera/contracts";

export async function GET(request: Request) { const authorization = await requirePermission(request, "agent:read"); if (!authorization.allowed) return authorization.response; return Response.json({ data: await listAssets(await tenantIdFromRequest(request)) }); }
export async function POST(request: Request) { const authorization = await requirePermission(request, "agent:read"); if (!authorization.allowed) return authorization.response; const body = (await request.json().catch(() => ({}))) as Partial<Asset>; try { const asset = await createAsset({ name: typeof body.name === "string" ? body.name : "", type: body.type === "Servidor" || body.type === "Red" || body.type === "Licencia" ? body.type : "Estación", owner: typeof body.owner === "string" ? body.owner : "" }, await tenantIdFromRequest(request)); return Response.json({ data: asset }, { status: 201 }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Could not create asset" }, { status: 400 }); } }
export async function PATCH(request: Request) { const authorization = await requirePermission(request, "agent:read"); if (!authorization.allowed) return authorization.response; const body = (await request.json().catch(() => ({}))) as Partial<Asset>; if (typeof body.id !== "string") return Response.json({ error: "id is required" }, { status: 400 }); const asset = await updateAsset(body.id, { name: typeof body.name === "string" ? body.name.trim() : undefined, type: body.type === "Servidor" || body.type === "Red" || body.type === "Licencia" ? body.type : "Estación", owner: typeof body.owner === "string" ? body.owner.trim() : undefined, status: body.status === "En revisión" || body.status === "Retirado" ? body.status : "Activo" }, await tenantIdFromRequest(request)); if (!asset) return Response.json({ error: "Asset not found" }, { status: 404 }); return Response.json({ data: asset }); }
export async function DELETE(request: Request) { const authorization = await requirePermission(request, "agent:read"); if (!authorization.allowed) return authorization.response; const id = new URL(request.url).searchParams.get("id"); if (!id || !(await deleteAsset(id, await tenantIdFromRequest(request)))) return Response.json({ error: "Asset not found" }, { status: 404 }); return Response.json({ data: { deleted: true } }); }
